services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rider
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  app:
    image: rider_single:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/rider"
      APPLY_INIT_DB: "true"
      DOMAIN: "local.test"
      RUST_BACKTRACE: "1"
    ports:
      - "80:80"
      - "3000:3000"
      - "8000:8000"
    networks:
      - default

volumes:
  db_data:
    driver: local
