# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

# Schema é definido diretamente nos models individuais
# [print_schema]
# file = "src/schema.rs"
# custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "D:\\rider_finance2\\backend\\migrations"
