ALTER TABLE usuarios
ADD COLUMN address VARCHAR NOT NULL DEFAULT '',
ADD COLUMN address_number VARCHAR NOT NULL DEFAULT '',
ADD COLUMN complement VARCHAR NOT NULL DEFAULT '',
ADD COLUMN postal_code VARCHAR NOT NULL DEFAULT '',
ADD COLUMN province VARCHAR NOT NULL DEFAULT '',
ADD COLUMN city VARCHAR NOT NULL DEFAULT '';
