export interface DashboardResponse {
  ganhos_hoje: number | null;
  ganhos_ontem: number;
  ganhos_semana: number;
  ganhos_semana_passada: number;
  ganhos_mes: number;
  ganhos_mes_passado: number;
  gastos_hoje: number;
  gastos_ontem: number;
  gastos_semana: number;
  gastos_semana_passada: number;
  gastos_mes: number;
  gastos_mes_passado: number;
  lucro_hoje: number;
  lucro_ontem: number;
  lucro_semana: number;
  lucro_semana_passada: number;
  lucro_mes: number;
  lucro_mes_passado: number;
  corridas_hoje: number;
  corridas_ontem: number;
  corridas_semana: number;
  corridas_semana_passada: number;
  corridas_mes: number;
  corridas_mes_passado: number;
  horas_hoje: number;
  horas_ontem: number;
  horas_semana: number;
  horas_semana_passada: number;
  horas_mes: number;
  horas_mes_passado: number;
  eficiencia: number;
  meta_diaria: number | null;
  meta_semanal: number | null;
  tendencia_ganhos: number;
  tendencia_gastos: number;
  tendencia_corridas: number;
  ganhos_7dias: number[];
  gastos_7dias: number[];
  lucro_7dias: number[];
  corridas_7dias: number[];
  horas_7dias: number[];
  ultimos_30_dias_labels: string[];
  ganhos_30dias: number[];
  gastos_30dias: number[];
  lucro_30dias: number[];
  corridas_30dias: number[];
  horas_30dias: number[];
  projecao_mes: number;
  projecao_semana: number;
  ganhos_mes_array?: number[];
  gastos_mes_array?: number[];
  lucro_mes_array?: number[];
  corridas_mes_array?: number[];
  trend_method: string;
}
