ALTER TABLE assinaturas
    ADD COLUMN asaas_customer_id VARCHAR,
    ADD COLUMN tipo_plano VARCHAR,
    DROP COLUMN IF EXISTS billing_type,
    DROP COLUMN IF EXISTS charge_type,
    DROP COLUMN IF EXISTS webhook_event_id,
    DROP COLUMN IF EXISTS checkout_id,
    DROP COLUMN IF EXISTS checkout_status,
    DROP COLUMN IF EXISTS checkout_date_created,
    DROP COLUMN IF EXISTS checkout_event_type,
    DROP COLUMN IF EXISTS valor,
    DROP COLUMN IF EXISTS descricao,
    DROP COLUMN IF EXISTS nome_cliente,
    DROP COLUMN IF EXISTS email_cliente,
    DROP COLUMN IF EXISTS cpf_cnpj_cliente;
